spring:
  application:
    name: product-category-service

  config:
    import: optional:configserver:http://config-server:8088

  datasource:
    url: jdbc:postgresql://postgresdb:5432/ecommerce
    username: postgres
    password: postgres

  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

